### ISSUE TITLE
IntelliSense for StyleSheet

### ISSUE THREAD

**Issue by dev-xdyang** [Microsoft/vscode-react-native#306]
## Actual Behavior
1. not show IntelliSense for StyleSheet key 
   <img width="427" alt="2016-09-24 10 30 28" src="https://cloud.githubusercontent.com/assets/7471748/18805513/bc3802c0-8242-11e6-8513-9e406ad0b514.png">
2. not show IntelliSense for StyleSheet value 
   <img width="503" alt="2016-09-24 10 31 03" src="https://cloud.githubusercontent.com/assets/7471748/18805516/d00beff0-8242-11e6-81ad-d8331d9ccfc2.png">
3. func IntelliSense always show when I edit the StyleSheet
   <img width="618" alt="2016-09-24 10 31 13" src="https://cloud.githubusercontent.com/assets/7471748/18805526/067f435c-8243-11e6-963c-015ceaf17d8e.png">
## Expected Behavior
1. support IntelliSense for StyleSheet key. for Instance, when I input "align", I expect get "alignItems" IntelliSense
2. support IntelliSense for StyleSheet available value for given key. for Instance, when I input "alignItems: ", I expect IntelliSense are flex-start, center, flex-end, and stretch
3. don't show func IntelliSense when I edit StyleSheet
## Software versions
- React-Native VS Code extension version: 0.2.0
- VSCode version: 1.5.3
- OS platform and version: MacOS 10.11.6
- React Native version: 0.34

**Comment by billti** [comment]
This is an issue with the types defined in the DefinitelyTyped repo (e.g. for the above see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react-native/index.d.ts#L3535 ). If someone wants to contribute better type definitions, that'd be awesome.

**Comment by vladimir-kotikov** [comment]
@dev-xdyang, @billti, a830751 should fix the problem with autocompleting properties.

As for 2 and 3 - the first is still a problem, even with the changes from a830751 It looks for me like a typescript issue, very similar to https://github.com/Microsoft/TypeScript/issues/11331

The second one probably has nothing to do with this extension - this is how VSCode displays a hint for function parameters. Hitting `Esc` once works for me - the hint disappears and is not being displayed anymore.

**Comment by vladimir-kotikov** [comment]
@MSLaguana, this should have been resolved by #306. Can we close this?

**Comment by MSLaguana** [comment]
@dev-xdyang We have updated the typings we use now as @vladimir-kotikov mentions, so it should be fixed. If you still have problems, feel free to re-open.

**Comment by josemigallas** [comment]
> VSCode 1.24.1
> React Native Tools 0.7.0

I'm still experiencing this error, only the values are shown:
![screen shot 2018-12-05 at 18 00 22](https://user-images.githubusercontent.com/11672286/49530141-e89b5e00-f8b7-11e8-8fa9-4d0612b8ad5c.png)
![screen shot 2018-12-05 at 17 59 59](https://user-images.githubusercontent.com/11672286/49530140-e89b5e00-f8b7-11e8-8320-65c2b7142c8b.png)
![screen shot 2018-12-05 at 17 59 51](https://user-images.githubusercontent.com/11672286/49530139-e89b5e00-f8b7-11e8-8a51-9f209f3c6596.png)

**Comment by ruslan-bikkinin** [comment]
Hi @josemigallas extension isn't responsible for intelisense for React native anymore, I believe you better address this to [vscode](https://github.com/Microsoft/vscode) repo as now it manages typings stuff.

**Comment by HaloWang** [comment]
I create a function to fix this problem temporarily

```typescript
import { ViewStyle, TextStyle, ImageStyle } from 'react-native'

/**
 * Quick Style
 *
 * related issue
 * @see https://github.com/Microsoft/vscode-react-native/issues/306
 * @see https://github.com/Microsoft/TypeScript/issues/29180
 * @see https://github.com/Microsoft/TypeScript/issues/28470
 *
 * Marco? `$`
 * @see https://github.com/Microsoft/TypeScript/issues/4892
 *
 * @todo `ViewStyle | TextStyle | ImageStyle` no work
 *  */
type _QS = ViewStyle & TextStyle & ImageStyle

export function $(style: _QS) {
  return style
}

```

usage
```typescript
const styles = StyleSheet.create({
  item: $({
    position: 'relative',
    overflow: 'visible',
  }),
})
```

And it works

<img width="626" alt="screen shot 2019-02-27 at 4 59 13 pm" src="https://user-images.githubusercontent.com/7344724/53478140-1eb03e80-3ab1-11e9-8a30-4d15b5cc558f.png">

😂

**Comment by NilsBacke** [comment]
Has this issue been fixed? Even with the fix from @HaloWang I still don't get intellisense suggestions after the first line.

**Comment by TheMisir** [comment]
I have same problem. I didn't found anything to fix that 😟

**Comment by GollyJer** [comment]
Same issue here. Ended up finding this extension which helps.
https://marketplace.visualstudio.com/items?itemName=jundat95.react-native-snippet

**Comment by ImAbhishekTomar** [comment]
same issue.
