### ISSUE TITLE
Unable to resolve module ./fonts/Entypo.ttf (@exponent/vector-icons)

### ISSUE THREAD

**Issue by cem2ran** [Microsoft/vscode-react-native#407]
## Actual Behavior
The React Native Tools packager when debugging an exponent project is unable to resolve files required by [@exponent/vector-icons](https://github.com/exponent/vector-icons). Can be reproduced by importing dependency, e.g.
`import { FontAwesome } from "@exponent/vector-icons";`

## Expected Behavior
The packager used in react-native-tools doesn't seem to take into account the Exponent asset system when trying to require fonts.

[Comment](https://exponentjs.slack.com/archives/help/p1488515546003493) from @brentvatne
![image](https://cloud.githubusercontent.com/assets/959142/23551046/89638180-0014-11e7-98c6-bbddc7221caa.png)

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version: 1.9.1
- OS platform and version: macOS Sierra 10.12.3 
- NodeJS version: 7.6
- React Native version: https://github.com/exponent/react-native/archive/sdk-14.0.0.tar.gz

## Outputs
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
(node:53107) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 5338): 
UnableToResolveError: Unable to resolve module ./fonts/Entypo.ttf from /Users/cem2ran/exponent-test/node_modules/@exponent/vector-icons/Entypo.js: 
Directory /Users/cem2ran/exponent-test/node_modules/@exponent/vector-icons/fonts/Entypo.ttf doesn't exist
```
- Output of directory listing:
```
~/exponent-test master*
❯ ls -la /Users/cem2ran/exponent-test/node_modules/@exponent/vector-icons/fonts/
total 1856
drwxr-xr-x  12 cem2ran  staff     408 14 Feb 21:34 .
drwxr-xr-x  24 cem2ran  staff     816 14 Feb 21:34 ..
-rw-r--r--   1 cem2ran  staff   65584  5 Jan 21:50 Entypo.ttf
-rw-r--r--   1 cem2ran  staff   13128  5 Jan 21:50 EvilIcons.ttf
-rw-r--r--   1 cem2ran  staff  165548  5 Jan 21:50 FontAwesome.ttf
-rw-r--r--   1 cem2ran  staff   56976  5 Jan 21:50 Foundation.ttf
-rw-r--r--   1 cem2ran  staff  143936  5 Jan 21:50 Ionicons.ttf
-rw-r--r--   1 cem2ran  staff  245676  5 Jan 21:50 MaterialCommunityIcons.ttf
-rw-r--r--   1 cem2ran  staff  128180  5 Jan 21:50 MaterialIcons.ttf
-rw-r--r--   1 cem2ran  staff   27428  5 Jan 21:50 Octicons.ttf
-rw-r--r--   1 cem2ran  staff   54056  5 Jan 21:50 SimpleLineIcons.ttf
-rw-r--r--   1 cem2ran  staff   25552  5 Jan 21:50 Zocial.ttf
```

**Comment by nicolaselmir** [comment]
I had the same problem. how to fix this

**Comment by vladimir-kotikov** [comment]
@cem2ran, thanks for reporting. Unfortunately, exponent support currently seems to be broken (see #414). We're investigating these issues and will let you know if there are any updates

**Comment by divyad** [comment]
I am also facing the same issue. Hope to get an update soon :)

**Comment by vladimir-kotikov** [comment]
This should be fixed in #415. Specifically there are two problems - a) we're using pretty outdated version of `xdl` and b) we're not passing options from `exp.json` to packager.

**Comment by SeanAvery** [comment]
@vladimir-kotikov I am also having this issue with the latest @exponent/ex-navigation v 2.9.1. and @expo/ex-navigation v 2.9.2 

I have also `npm i react-native-vector-icons` which includes Entypo icon library...

What is the status on PR #415 ?

**Comment by kibagateaux** [comment]
As of April 27th I am still having this issue with the exact same error message

React-Native VS Code extension version: 0.3.2
VSCode version: 1.11.2
OS platform and version: macOS Sierra 10.12.4
NodeJS version: 7.8
React Native version: 0.43.4

**Comment by Sofiane-13** [comment]
@vladimir-kotikov   @cem2ran  @divyad @nicolaselmir 
Please, you have found the solution?

![cpqeq](https://cloud.githubusercontent.com/assets/11254768/26059769/257384f6-3983-11e7-90bc-e8f8e4dee3d2.png)

**Comment by Sofiane-13** [comment]
http://stackoverflow.com/questions/43967521/unable-to-resolve-module-fonts-entypo-ttf-from-home-pfe-node-modules-expo
