### ISSUE TITLE
Fail to start debugging: Spawn react-native ENOENT when starting "Debug iOS"

### ISSUE THREAD

**Issue by omdv** [Microsoft/vscode-react-native#597]
## Actual Behavior
This issue appeared just recently, I can't track it back to any upgrades or changes I did. 

When trying to start debugging (iOS mode) I get the following error: Error while executing command 'react-native run-ios --simulator --no-packager': spawn react-native ENOENT

## Software versions
- React-Native VS Code extension version: 0.5.4
- VSCode version: 1.18.1
- OS platform and version: macOS Sierra (10.12.6)
- NodeJS version: 8.9.1
- React Native version: 
react-native-cli: 2.0.1
react-native: 0.47.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.4
Could not debug. Error while executing command 'react-native run-ios --simulator --no-packager': spawn react-native ENOENT
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Starting Packager

Scanning 1095 folders for symlinks in /Users/om/Documents/react-native/cryptofolio/node_modules (18ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/om/Documents/react-native/cryptofolio 


React packager ready.

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.ios.bundle?platform=ios

Bundling `index.ios.js`  [development, non-minified, hmr disabled]  100.0% (1580/1580), done.
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Error] Error: Error while executing command 'react-native run-ios --simulator --no-packager': spawn react-native ENOENT
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] ApplicationInsights:Sender Array(1)
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] (node:7128) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] ApplicationInsights:Sender Array(1)
```

Other notes
1. `react-native run-ios` works fine from terminal
2. `.vscode/.react` folder is created on starting VS code, it is empty though
2. calling `code .` from terminal as suggested in some responses to similar issues does not help

**Comment by wilomgfx** [comment]
I can confirm i get the same thing by just trying to launch my iOS app from vscode.

**Comment by callagga** [comment]
I'm getting this on one of my IOS projects too:
[Info] Building and running application.
[Error] Error: Error while executing command 'react-native run-ios --simulator --no-packager': Error while executing command 'react-native run-ios --simulator --no-packager'

I just noted a project that worked has "Metro Bundler ready" listed during the startup, whereas the project that is not working has "React packager ready".

I'm not sure however how you get the "Metro Bundler" selected (or what this is). Both launch.json entries seem to be the same??/

**Comment by wilomgfx** [comment]
@callagga React packager is the old packager. React native (new versions) use Metro Bundler instead. Upgrade your old project.

**Comment by callagga** [comment]
oh - ok so basically it's a "react native" upgrade you're referring to here right?

**Comment by wilomgfx** [comment]
@callagga  yes.

**Comment by callagga** [comment]
many thanks

**Comment by omdv** [comment]
confirm that the issue is gone. Was fixed 12 days ago by https://github.com/Microsoft/vscode-react-native/pull/600 Thanks.

**Comment by romk1n** [comment]
I am using vscode - `Version 1.18.1 (1.18.1)` and latest plugin and still see the issue, ay idea how to fix it?

**Comment by iTOYS** [comment]
Hi @romk1n 
Does `react-native run-ios --simulator` command work fine in terminal?
Could you please provide some outputs and software versions?

**Comment by romk1n** [comment]
@iTOYS yeah it does. .what kind of info you need ?

**Comment by iTOYS** [comment]
@romk1n 
* Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox)

BTW, i couldn't repro this issue after 0.5.7 release

**Comment by tr0yspradling** [comment]
I'm getting this as well. 

```
MyTownTV-Mobile~> react-native --version             
react-native-cli: 2.0.1
react-native: 0.45.0

MyTownTV-Mobile~>  react-native run-ios               
Found Xcode project MyTownTV-Mobile.xcodeproj

spawnSync xcrun ENOENT

```
