### ISSUE TITLE
.env file not found when running 'Run Android on Device'

### ISSUE THREAD

**Issue by Fernando-Marquardt** [Microsoft/vscode-react-native#603]
After upgrading the plugin to version 0.5.5, the 'React Native: Run Android on Device' task stopped working with the error described below.

It may have something to do with https://github.com/Microsoft/vscode-react-native/pull/596 or https://github.com/Microsoft/vscode-react-native/issues/566

## Actual Behavior
1. Run 'React Native: Run Android on Device'
2. Run the packager
3. Error when trying to run the Android build

## Expected Behavior
1. Run 'React Native: Run Android on Device'
2. Run the packager
3. Run the Android build

## Software versions
- React-Native VS Code extension version: 0.5.5
- VSCode version: 1.18.1
- OS platform and version: Windows 10
- NodeJS version: 7.9.0
- React Native version: 0.47.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
EMPTY
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Attempting to start the React Native packager

[Info] Starting Packager

Scanning 718 folders for symlinks in f:\project_folder\node_modules (42ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   f:\project_folder 


React packager ready.

[Info] Packager started.

[Error] Failed to run the application in Android

Stack: Error: Failed to run the application in Android: ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\${workspaceFolder}\.env'
	at Function.getWrappedError (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\src\common\error\internalError.js:35:16)
	at Function.wrapError (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\src\common\error\errorHelper.js:18:44)
	at resultOfCode.done.reason (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\src\common\entryPointHandler.js:40:72)
	at _rejected (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\node_modules\q\q.js:844:24)
	at C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\node_modules\q\q.js:870:30
	at Promise.when (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\node_modules\q\q.js:1122:31)
	at Promise.promise.promiseDispatch (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\node_modules\q\q.js:788:41)
	at C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\node_modules\q\q.js:604:44
	at runSingle (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\node_modules\q\q.js:137:13)
	at flush (C:\Users\Fernando\.vscode\extensions\vsmobile.vscode-react-native-0.5.5\node_modules\q\q.js:125:13)
Loading dependency graph, done.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
No relevant info
```

**Comment by iTOYS** [comment]
@Fernando-Marquardt 
Thanks for reporting!
Have been fixed in 0.5.6

**Comment by michaelduminy** [comment]
@iTOYS I'm still getting this error in 0.5.6

**Comment by Fernando-Marquardt** [comment]
@iTOYS I am still getting the same error after updating to the 0.5.6.

**Comment by jc4p** [comment]
@iTOYS Also getting this same error after upgrading to 0.5.6, when trying to run on an iOS device.

**Comment by iTOYS** [comment]
Sorry guys!
Please try again with 0.5.7

**Comment by Fernando-Marquardt** [comment]
Hey! 0.5.7 worked for me. Thank you!

**Comment by michaelduminy** [comment]
Works! Thanks

**Comment by YogeshLegendkiller** [comment]
am getting this error in 0.6.5

**Comment by max-mironov** [comment]
@YogeshLegendkiller could you please provide as more info i.e. how to reproduce it step by step, your env, rn versions, NodeJS version, OS etc?
