### ISSUE TITLE
code push can't detect "index.ios.js" or "index.js"

### ISSUE THREAD

**Issue by G3z** [Microsoft/vscode-react-native#637]
## Actual Behavior
1. React native code push: release react!
2. An error occured on doing Code Push release. Entry file "index.ios.js" or "index.js" does not exist. 

## Expected Behavior
1. React native code push: release react!
2. yay!

i have both index.ios.js and index.js in the root of my RN app

**Comment by max-mironov** [comment]
Hey @G3z thanks so much for your feedback and your question!
I've just tried to create a new RN app, add CodePush to it and release an update with VSCode extension, seems looking good so far.

Please see my app here: https://github.com/max-mironov/RNCPIssue637
If possible could you please share your app with us so we could look at (or at least how you integrate could push, code samples, react-native/code-push versions etc)?

Also I'll try to repo your issue with older versions of RN just in case.

Looking forward for your reply!

**Comment by G3z** [comment]
if you remove your `index.js` you will get the error. 
the extension should pick up `index.ios.js` automagically, right ?

**Comment by pniko** [comment]
Should definitely pick it up @G3z. We'll do some more investigation on our end.

**Comment by annakocheshkova** [comment]
Hi @G3z. We have fixed the issue and are going to make a new release with the fix today. We will keep you updated on the progress.

**Comment by sergey-akhalkov** [comment]
Hi @G3z, we've fixed this issue in https://github.com/Microsoft/vscode-react-native/releases/tag/0.6.1
So I'm closing this issue, please feel free to reopen if the issue still has place of if you have any questions.

**Comment by LasseSLambertsen** [comment]
Still having this issue though with index.android.js. Updated extension, and on newest RN.

**Comment by annakocheshkova** [comment]
@LasseSLambertsen Hi, yes you are correct, we have fixed this issue and are going to release the fix ASAP.

**Comment by max-mironov** [comment]
@LasseSLambertsen,  thanks, Released 0.6.6 :)
